apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ldj6xbuti-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ldj6xbuti-python 
  name: ldj6xbuti-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ldj6xbuti-python 
